import React from 'react';
import { Shield, Lock, AlertTriangle, Sparkles, Heart } from 'lucide-react';

interface FooterProps {
  onOpenDisclaimer: () => void;
}

export const Footer: React.FC<FooterProps> = ({ onOpenDisclaimer }) => {
  return (
    <footer className="bg-slate-950 text-slate-400 text-xs border-t border-slate-800/80 mt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          
          {/* Column 1: Brand */}
          <div className="space-y-3 md:col-span-1">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-emerald-600 flex items-center justify-center text-white">
                <Shield className="w-4 h-4" />
              </div>
              <span className="font-bold text-base text-slate-100">ShieldLance</span>
            </div>
            <p className="text-slate-400 text-xs leading-relaxed">
              Empowering freelancers, remote workers, and contractors to detect fraud, spot predatory clauses, and protect their earnings before signing or accepting work.
            </p>
          </div>

          {/* Column 2: Key Features */}
          <div>
            <h4 className="font-semibold text-slate-200 text-xs uppercase tracking-wider mb-3">Core Protection</h4>
            <ul className="space-y-2 text-slate-400">
              <li>• Real-time AI Text & Screenshot Analysis</li>
              <li>• Predatory Clause Detection</li>
              <li>• Color-coded Risk Meter (0–100)</li>
              <li>• Ready-to-send Probe Messages</li>
              <li>• Verified Scam Pattern Index</li>
            </ul>
          </div>

          {/* Column 3: Trust & Security */}
          <div>
            <h4 className="font-semibold text-slate-200 text-xs uppercase tracking-wider mb-3">Privacy & Security</h4>
            <div className="space-y-2 text-slate-400">
              <p className="flex items-center gap-1.5">
                <Lock className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                <span>Zero key leakage: Server-side proxy API</span>
              </p>
              <p className="flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                <span>No personal data stored or sold</span>
              </p>
              <p className="flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                <span>Powered by Google Gemini AI</span>
              </p>
            </div>
          </div>

          {/* Column 4: AI Disclaimer */}
          <div>
            <h4 className="font-semibold text-slate-200 text-xs uppercase tracking-wider mb-3">AI Transparency Notice</h4>
            <p className="text-slate-400 leading-relaxed mb-2">
              Risk assessments and red flags are generated by artificial intelligence as a decision-support utility.
            </p>
            <button
              onClick={onOpenDisclaimer}
              className="text-emerald-400 hover:text-emerald-300 font-medium underline underline-offset-2 flex items-center gap-1"
            >
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
              <span>Read Full Legal & AI Notice</span>
            </button>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-800/60 flex flex-col sm:flex-row items-center justify-between gap-4 text-slate-500 text-xs">
          <p>© {new Date().getFullYear()} ShieldLance. All rights reserved. Built for remote job seekers worldwide.</p>
          <div className="flex items-center gap-1 text-slate-500">
            <span>Built with vigilance for the global freelance community</span>
            <Heart className="w-3.5 h-3.5 text-rose-500 fill-rose-500/20" />
          </div>
        </div>
      </div>
    </footer>
  );
};
